name: Build executable

on:
  push:
    tags:
      - 'v*'  # np. v1.0, v1.1 itd.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --hidden-import=antlr4 PseudoInterpreter.py

    - name: Rename binary to include OS
      run: |
        EXT=""
        if [[ "${{ runner.os }}" == "Windows" ]]; then EXT=".exe"; fi
        mv dist/PseudoInterpreter dist/PseudoInterpreter-${{ runner.os }}$EXT
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pseudoInterpreter-${{ runner.os }}
        path: dist/PseudoInterpreter-${{ runner.os }}*

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/PseudoInterpreter-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
