name: Build executable

on:
  push:
    tags:
      - 'v*'  # działa po wypchnięciu taga np. v1.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --hidden-import=antlr4 PseudoInterpreter.py

      - name: Make binary executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x dist/PseudoInterpreter

      - name: Rename binary to include OS
        shell: bash
        run: |
          EXT=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then EXT=".exe"; fi
          mv dist/PseudoInterpreter dist/PseudoInterpreter-${{ runner.os }}$EXT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pseudoInterpreter-${{ runner.os }}
          path: dist/PseudoInterpreter-${{ runner.os }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*  # pobiera wszystkie pliki z artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
