name: Build executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile pseudoInterpreter.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pseudoInterpreter-${{ runner.os }}
        path: dist/pseudoInterpreter*

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/pseudoInterpreter*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
