name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get install pandoc texlive-xetex -y
      - name: Convert
        run: pandoc README.md -o dokument.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: dokument-pdf
          path: dokument.pdf